[base]
dimension = 2
output_dir = "output"

[algorithm]
seed = 12345

[algorithm.param]
max_list = [6.0, 6.0]
min_list = [-6.0, -6.0]
num_list = [31, 31]

[solver]

[runner]
[runner.log]
interval = 20
