[base]
dimension = 3
output_dir = "output"

[algorithm]
seed = 12345

#[algorithm.param]
#max_list = [ 1.0,  1.0,  1.0]
#min_list = [-1.0, -1.0, -1.0]
#num_list = [21, 21, 21]

[solver]

[runner]
[runner.log]
interval = 20
